package main

import (
	"bytes"
	"testing"
	"io"
	"net/http"
	"net/http/httptest"

	"snippetbox.senor-crab.com/internal/assert"
)

func TestPing(t *testing.T) {
	// Response recorder
	rr := httptest.NewRecorder()

	// dummy http.Request
	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}
	ping(rr, r)

	// Fetch http.Response generated by ping()
	rs := rr.Result()
	assert.Equal(t, rs.StatusCode, http.StatusOK)
	defer rs.Body.Close()
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "OK")
}
